---
idt001:
  command: configTable
  table_style: 'table-layout: fixed; width: 75% ; margin: 0 auto; border:0px solid rgb(0, 0, 0); border-radius: 10px; background-color:transparent; border-color: blue;'
  tr_style: 'height: 120px;'
  th_style: 'border: 0px solid black; text-align: center;align-items: center; align-self: center; width: 65%;'
  td_style: 'font-size: 18px; text-align:center; border:0px solid rgb(0, 0, 0); border-radius: 10px; padding: 5px; border-style:solid; border-color: blue; background-color:transparent;'
  div_style: 'background-color: transparent; border:0px solid rgb(0, 0, 0); border-radius: 10px; padding: 5px; border-style:solid; border-color:blue;'
  body-style: 'padding: 25px; background-color: rgb(255, 222, 173); border: 0px solid rgb(0, 0, 0); border-radius: 10px; border-style:solid; border-color:green;'

id001:
  command: addHeaderImage
  title: Learn Spanish
  image:  ./images/learnspanish.PNG
  space: ''
  img_style: 'width: 65%; height: 180px; display: block; margin-left: auto; margin-right: auto; box-shadow: 0px 0px 20px lightblue; border-radius:15px; border-style:dashed; border-color:black; border-width:3px;'
  
id0002h:
  command: addStyle
  comment: ''
  file_name: style.css

id003:
  command: addReturnLink
  title: Language Dashboard
  link: ../Language-Dashboard/index.html
  space: ''
  p_style: 'margin: 5px 0px 0px; font-size: 16px; font-family: Times New Roman; text-align: center; font-weight: normal; font-style: italic; color: green;'
  target: _parent
  
Id004:
  command: addTitle
  title: Spanish Learning Center
  link: ''
  space: ''
  p_style: 'margin: 5px 0px 0px; font-size: 28px; font-family: Times New Roman; text-align: center; font-weight: Bold; font-style: normal; color: black; border:1px solid rgb(0, 0, 0); border-radius: 10px; border-color: blue; background-color:yellow; margin-left: auto; margin-right: auto; vertical-align:middle; width:75%; height: auto;'

id005:
  command: setMaxColumns
  max_columns: 6

id1:
  command: addItem
  title: Laura
  link: https://www.youtube.com/@spanishafterhours/videos
  image: ./images/spanishafterhours.PNG
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'

id2:
  command: addItem
  title: Spanish for Beginners
  link: https://www.youtube.com/watch?v=hyLl_0d0EBw&list=PLTpetkN815Qyuc2RbC1kxxMQvxjQ3RnYG
  image: ./images/DrDannnyEvans.png
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'

id3:
  command: addItem
  title: Mango
  link: https://mangolanguages.com/
  image: ./images/mangolanguages.png
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'

id4:
  command: addItem
  title: Heidi Espanol
  link: https://www.youtube.com/@HeidiEspanol/videos
  image: ./images/heidiespanol.png
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'

id5:
  command: addItem
  title: Telemadrid
  link: https://www.youtube.com/@telemadrid/videos
  image: ./images/telemadrid.png
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'

id6:
  command: addItem
  title: Frank Cuesta canal
  link: https://www.youtube.com/@santuariolibertad/videos
  image: ./images/santuariolibertad.png
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'
  
id7:
  command: addItem
  title: Duolingo
  link: https://www.duolingo.com
  image: ./images/duolingo.png
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'

id8:
  command: addItem
  title: Spanish Playground
  link: https://www.youtube.com/@SpanishPlayground/videos
  image: ./images/spanishplayground.png
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'

id9:
  command: addItem
  title: Butterfly Spanish
  link: https://www.youtube.com/@ButterflySpanish/videos
  image: ./images/butterflyspanish.png
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'

id10:
  command: addItem
  title: Spanish con Ali :)
  link: https://www.youtube.com/@espanolconali/videos
  image: ./images/espanolconali.png
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'

id11:
  command: addItem
  title: lingua
  link: https://lingua.com/spanish/reading/
  image: ./images/lingua.png
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'

id12:
  command: addItem
  title: Spanish Dictionary
  link: https://www.spanishdict.com/
  image: ./images/spanishdict.png
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'

id13:
  command: addItem
  title: Google Translator
  link: https://translate.google.com/
  image: ./images/googletranslator.png
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'

id14:
  command: addItem
  title: FluentU Spanish
  link: https://www.youtube.com/@FluentUSpanish/videos
  image: ./images/FluentUSpanish.png
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'
  
id16:
  command: addItem
  title: Hola Spanish
  link: https://www.youtube.com/@HolaSpanish
  image: ./images/holaspanish.png
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'

id17:
  command: addItem
  title: Erica Ray Language
  link: https://www.youtube.com/@EricaRayLanguage/videos
  image: ./images/EricaRayLanguage.PNG
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'

id18:
  command: addItem
  title: Listening Spanish ju8sd
  link: https://www.youtube.com/@Listening-Spanish-ju8sd/videos
  image: ./images/listening-spanish.PNG
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'

id19:
  command: addItem
  title: How To Spanish Official
  link: https://www.youtube.com/@HowtoSpanishOfficial/videos
  image: ./images/HowtoSpanishOfficial.PNG
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'
    
id20:
  command: addItem
  title: Espanol Con Juan
  link: https://www.youtube.com/@espanolconjuan/videos
  image: ./images/espanolconjuan.PNG
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'
  
id21:
  command: addItem
  title: Tearcher Anny
  link: https://www.youtube.com/@teacheranny7709/videos
  image: ./images/teacheranny.PNG
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'  
  
id22:
  command: addItem
  title: Caso Cerrado
  link: https://www.youtube.com/@CasoCerrado/videos
  image: ./images/CasoCerrado.PNG
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'  

id23:
  command: addItem
  title: Alegre Spanish
  link: https://www.youtube.com/@alegrespanish/videos
  image: ./images/AlegresSpanish.PNG
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'

id24:
  command: addItem
  title: Erre que ELE
  link: https://www.youtube.com/@ErrequeELE/videos
  image: ./images/ErrequeELE.PNG
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'  
  
id25:
  command: addItem
  title: Spring Spanish - Learn Spanish with Chunks
  link: https://www.youtube.com/@springspanish/videos
  image: ./images/springspanish.PNG
  space: ''
  p_style: 'margin: 0px 0px 0px; font-size: 14px; font-family: sans-serif; text-align: center; font-weight: normal; font-style: normal; color: blue;'
  img_style: 'width: 70%; height: 120px; box-shadow: 0px 0px 20px #888; border-radius: 15px;'  

id006:
  command: addTimeStamp
  title: 'Last Created on: '
  space: ''
  p_style: 'margin: 5px 0px 0px; font-size: 14px; font-family: Times New Roman; text-align: center; font-weight: normal; font-style: italic; color: black; border: 0px solid rgb(0, 0, 0); border-radius: 10px; border-color: green; background-color: yellow;  margin-left: auto; margin-right: auto; vertical-align:middle; width:25%; height: auto;'